# Generated by Django 3.2.25 on 2024-04-08 12:59

import divego_project.models
from django.db import migrations, models
import django.utils.timezone
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'super'), (2, 'admin')], primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'diver'), (2, 'instructor'), (3, 'store'), (4, 'staff')], primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=50, unique=True)),
                ('first_name', models.TextField(blank=True, max_length=50)),
                ('last_name', models.TextField(blank=True, max_length=50)),
                ('username', models.TextField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(null=True)),
                ('verified', models.TextField(max_length=50, null=True)),
                ('last_ip', models.TextField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='user_profile')),
                ('image_public', models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='divego-resources'), upload_to='user_profile_public')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('privileges', models.ManyToManyField(blank=True, to='divego_project.Privileges')),
                ('roles', models.ManyToManyField(blank=True, to='divego_project.Roles')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', divego_project.models.UserManager()),
            ],
        ),
    ]
