# Generated by Django 3.2.25 on 2024-05-12 11:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divego_project', '0002_resetpasswordsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.TextField(blank=True, choices=[('diver', 'Diver'), ('instructor', 'Instructor'), ('store', 'Store'), ('staff', 'Staff')]),
        ),
        migrations.RemoveField(
            model_name='user',
            name='privileges',
        ),
        migrations.AddField(
            model_name='user',
            name='privileges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('super', 'Super'), ('admin', 'Admin')]), blank=True, default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Privileges',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
