# Generated by Django 3.2.25 on 2024-05-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divego_project', '0003_auto_20240512_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diver_type',
            field=models.TextField(blank=True, choices=[('freediver', 'Freediver'), ('scuba_diver', 'Scuba Diver')]),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(max_length=90, unique=True),
        ),
    ]
