# Generated by Django 3.2.25 on 2024-05-12 18:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('divego_project', '0004_auto_20240512_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freediver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('preferred_dive_locations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None)),
                ('diver_type', models.TextField(blank=True, choices=[('fun_diver', 'Fun Diver'), ('line_diver', 'Line Diver')])),
                ('certification', models.TextField(blank=True, choices=[('non_cert', 'Non-certified'), ('other_cert', 'Other Certification'), ('molchanovs_waveD', 'Molchanovs Discover Wave'), ('molchanovs_wave1', 'Molchanovs Wave 1'), ('molchanovs_wave2', 'Molchanovs Wave 2'), ('molchanovs_wave3', 'Molchanovs Wave 3'), ('molchanovs_wave4', 'Molchanovs Wave 4'), ('molchanovs_wave2i', 'Molchanovs Wave 2 Instructor'), ('molchanovs_wave3i', 'Molchanovs Wave 3 Instructor'), ('molchanovs_wave4i', 'Molchanovs Wave 4 Instructor'), ('molchanovs_it', 'Molchanovs Instructor Trainer'), ('molchanovs_w3it', 'Molchanovs Wave 3 Instructor Trainer'), ('molchanovs_w4it', 'Molchanovs Wave 4 Instructor Trainer'), ('molchanovs_itd', 'Molchanovs Instructor Trainer Developer'), ('aida1', 'AIDA 1'), ('aida2', 'AIDA 2'), ('aida3', 'AIDA 3'), ('aida4', 'AIDA 4'), ('aida_instructor', 'AIDA Instructor'), ('aida_master_instructor', 'AIDA Master Instructor'), ('aida_instructor_trainer', 'AIDA Instructor Trainer'), ('padi_basic', 'PADI Basic Freediver'), ('padi_freediver', 'PADI Freediver'), ('padi_advanced_freediver', 'PADI Advanced Freediver'), ('padi_master_freediver', 'PADI Master Freediver'), ('padi_freediver_instructor', 'PADI Freediver Instructor'), ('padi_advanced_freediver_instructor', 'PADI Advanced Freediver Instructor'), ('padi_master_freediver_instructor', 'PADI Master Freediver Instructor'), ('padi_freediver_instructor_trainer', 'PADI Freediver Instructor Trainer')])),
                ('certification_verified', models.TextField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='diver_profile')),
                ('image_public', models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='divego-resources'), upload_to='diver_profile_public')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreediveInstructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('preferred_dive_locations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None)),
                ('email', models.TextField(max_length=90, unique=True)),
                ('phone', models.TextField(blank=True, max_length=50)),
                ('certification', models.TextField(blank=True, choices=[('molchanovs_wave2i', 'Molchanovs Wave 2 Instructor'), ('molchanovs_wave3i', 'Molchanovs Wave 3 Instructor'), ('molchanovs_wave4i', 'Molchanovs Wave 4 Instructor'), ('molchanovs_it', 'Molchanovs Instructor Trainer'), ('molchanovs_w3it', 'Molchanovs Wave 3 Instructor Trainer'), ('molchanovs_w4it', 'Molchanovs Wave 4 Instructor Trainer'), ('molchanovs_itd', 'Molchanovs Instructor Trainer Developer'), ('aida_instructor', 'AIDA Instructor'), ('aida_master_instructor', 'AIDA Master Instructor'), ('aida_instructor_trainer', 'AIDA Instructor Trainer'), ('padi_freediver_instructor', 'PADI Freediver Instructor'), ('padi_advanced_freediver_instructor', 'PADI Advanced Freediver Instructor'), ('padi_master_freediver_instructor', 'PADI Master Freediver Instructor'), ('padi_freediver_instructor_trainer', 'PADI Freediver Instructor Trainer')])),
                ('certification_verified', models.TextField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='diver_profile')),
                ('image_public', models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='divego-resources'), upload_to='diver_profile_public')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiveShop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('shop_type', models.TextField(blank=True, choices=[('freediving_shop', 'Freediving Shop'), ('scuba_shop', 'Scuba Shop'), ('all_dive_shop', 'All Dive Shop')])),
                ('email', models.TextField(max_length=90, unique=True)),
                ('phone', models.TextField(blank=True, max_length=50)),
                ('image', models.ImageField(null=True, upload_to='diver_profile')),
                ('image_public', models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='divego-resources'), upload_to='diver_profile_public')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
