# Generated by Django 3.2.25 on 2024-05-25 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divego_project', '0005_diveshop_freediveinstructor_freediver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freediver',
            old_name='diver_type',
            new_name='freediver_type',
        ),
    ]
