# Generated by Django 3.2.25 on 2024-05-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divego_project', '0006_rename_diver_type_freediver_freediver_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freediver',
            name='freediver_type',
            field=models.TextField(blank=True, choices=[('fun_diver', 'Fun Diver'), ('line_diver', 'Line Diver'), ('spear_fisher', 'Spear Fisher')]),
        ),
    ]
