# Generated by Django 3.2.25 on 2024-05-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divego_project', '0007_alter_freediver_freediver_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='freediver',
            name='certification_number',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freediver',
            name='certification_verified',
            field=models.BooleanField(default=False),
        ),
    ]
