# Generated by Django 3.2.25 on 2024-06-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divego_project', '0009_auto_20240604_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_location_id',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
