# Generated by Django 3.2.25 on 2024-07-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divego_project', '0010_user_current_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='main',
            field=models.TextField(max_length=70, null=True),
        ),
    ]
