# Generated by Django 3.2.25 on 2024-08-19 14:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divego_project', '0011_auto_20240718_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privileges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('super', 'Super'), ('admin', 'Admin'), ('scout', 'Scout')]), blank=True, default=list, size=None),
        ),
    ]
